embed_assets: on
#javascript_compressor: yui
template_extension: html.mustache
template_function: "Handlebars.compile"
#template_function: "_.template"
javascripts:
  common:
    - public/javascripts/vendor/jquery/jquery-1.4.4.js
    - public/javascripts/vendor/jquery-ui/development-bundle/ui/jquery-ui-1.8.2.custom.js
    - public/javascripts/rails.js
    - public/javascripts/vendor/underscore/underscore.js
    - public/javascripts/vendor/json2.js
    - public/javascripts/vendor/backbone-0.5.1.js
    - public/javascripts/vendor/js-templates/handlebars.js
    - public/javascripts/init.js
  snarpur:
    - public/javascripts/coffeescripts/app.js
    - public/javascripts/coffeescripts/models/*
    - public/javascripts/coffeescripts/controllers/*
    - public/javascripts/coffeescripts/views/**/*
    - app/coffeescripts/templates/**/*
  chart:
    - public/javascripts/vendor/jqplot/jquery.jqplot.js
    - public/javascripts/vendor/jqplot/plugins/jqplot.categoryAxisRenderer.js
    - public/javascripts/vendor/jqplot/plugins/jqplot.axisLabelRenderer.js
    - public/javascripts/vendor/jqplot/plugins/jqplot.canvasAxisTickRenderer.js
    - public/javascripts/vendor/jqplot/plugins/jqplot.canvasTextRenderer.js
    - public/javascripts/vendor/jqplot/plugins/jqplot.barRenderer.js
    - public/javascripts/vendor/jqplot/plugins/jqplot.pointLabels.js

  # nested_fields:
  #   - public/javascripts/action_items
  #   - public/javascripts/action_elements


    # - public/javascripts/vendor/handlebars.js
    # - public/javascripts/vendor/jquery.datalink.js
    #
#   application:
#     - public/javascripts/app/lib/*
#     - public/javascripts/app/app.js
#     - public/javascripts/app/models/*
#     - app/coffeescripts/templates/**/*
#     - public/javascripts/app/views/**/*
#     - public/javascripts/app/controllers/*
#
stylesheets:
  common:
    - public/stylesheets/buttons.css
    - public/stylesheets/compiled/application.css
    - public/stylesheets/compiled/sprite.css
  chart:
    - public/javascripts/vendor/jqplot/jquery.jqplot.min.css
    #- public/stylesheets/compiled/timeline.css

