embed_assets: on
#javascript_compressor: yui
template_function: Haml
template_extension: .jst.haml
templates_strip_newlines: on


javascripts:
  common:
    - public/javascripts/vendor/jquery/jquery.js
    - public/javascripts/vendor/jquery/jquery.tmpl.js
    - public/javascripts/vendor/jquery-ui/development-bundle/ui/jquery-ui-1.8.2.custom.js
    - public/javascripts/vendor/jquery/jquery.metadata.js
    - public/javascripts/rails.js
    - public/javascripts/vendor/underscore/underscore.js
    - public/javascripts/vendor/json2.js
    - public/javascripts/vendor/backbone.js
    - public/javascripts/vendor/haml/haml.js
    - public/javascripts/init.js
  snarpur:
    - public/javascripts/coffeescripts/app.js
    - public/javascripts/coffeescripts/models/*
    - public/javascripts/coffeescripts/controllers/*
    - public/javascripts/coffeescripts/views/**/*
    - app/views/**/*.jst.haml
  # nested_fields:
  #   - public/javascripts/action_items
  #   - public/javascripts/action_elements


    # - public/javascripts/vendor/handlebars.js
    # - public/javascripts/vendor/jquery.datalink.js
    #
#   application:
#     - public/javascripts/app/lib/*
#     - public/javascripts/app/app.js
#     - public/javascripts/app/models/*
#     - app/coffeescripts/templates/**/*
#     - public/javascripts/app/views/**/*
#     - public/javascripts/app/controllers/*
#
stylesheets:
  common:
    - public/javascripts/jquery-ui/css/smoothness/jquery-ui-1.8.2.custom.css
    - public/stylesheets/buttons.css
    - public/stylesheets/compiled/application.css
    - public/stylesheets/compiled/timeline.css
    - http://fonts.googleapis.com/css?family=Droid+Sans:regular,bold
