# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  # adapter: mysql2
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: snarpur_development
  host: localhost
  pool: 5
  # username: root
  # username: postgres
  username: orripalsson
  # password: 
  password: alaska1959
  
  # socket: /tmp/mysql.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  # adapter: mysql2
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: snarpur_test
  host: localhost
  pool: 5
  # username: root
  # username: postgres
  username: orripalsson
  # password:
  password: alaska1959   
  # socket: /tmp/mysql.sock


staging:
  # adapter: mysql2
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: snarpur_staging
  host: localhost
  pool: 5
  # username: root
  # username: postgres
  username: orripalsson
  # password:
  password: alaska1959
  # socket: /tmp/mysql.sock


production:
 adapter: postgresql
 encoding: utf8
 reconnect: false
 database: dfvd5p79k17ou1
 host: ec2-107-20-165-44.compute-1.amazonaws.com
 pool: 5
 username: ifyccvidmrzuvr
 password: L3Oqi3cahNQCyfEKijdrcFhg59
  # socket: /tmp/mysql.sock

# production:
  # adapter: mysql2
  # adapter: postgresql
  # encoding: utf8
  # reconnect: false
  # database: snarpur_production
  # host: localhost
  # pool: 5
  # username: root
  # username: postgres
  # password:
  # password: alaska1959
  # socket: /tmp/mysql.sock



cucumber:
  <<: *test
