require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EntryValuesController do

  # This should return the minimal set of attributes required to create a valid
  # EntryValue. As you add validations to EntryValue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "entry_field_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EntryValuesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all entry_values as @entry_values" do
      entry_value = EntryValue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:entry_values).should eq([entry_value])
    end
  end

  describe "GET show" do
    it "assigns the requested entry_value as @entry_value" do
      entry_value = EntryValue.create! valid_attributes
      get :show, {:id => entry_value.to_param}, valid_session
      assigns(:entry_value).should eq(entry_value)
    end
  end

  describe "GET new" do
    it "assigns a new entry_value as @entry_value" do
      get :new, {}, valid_session
      assigns(:entry_value).should be_a_new(EntryValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested entry_value as @entry_value" do
      entry_value = EntryValue.create! valid_attributes
      get :edit, {:id => entry_value.to_param}, valid_session
      assigns(:entry_value).should eq(entry_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EntryValue" do
        expect {
          post :create, {:entry_value => valid_attributes}, valid_session
        }.to change(EntryValue, :count).by(1)
      end

      it "assigns a newly created entry_value as @entry_value" do
        post :create, {:entry_value => valid_attributes}, valid_session
        assigns(:entry_value).should be_a(EntryValue)
        assigns(:entry_value).should be_persisted
      end

      it "redirects to the created entry_value" do
        post :create, {:entry_value => valid_attributes}, valid_session
        response.should redirect_to(EntryValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved entry_value as @entry_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntryValue.any_instance.stub(:save).and_return(false)
        post :create, {:entry_value => { "entry_field_id" => "invalid value" }}, valid_session
        assigns(:entry_value).should be_a_new(EntryValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EntryValue.any_instance.stub(:save).and_return(false)
        post :create, {:entry_value => { "entry_field_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested entry_value" do
        entry_value = EntryValue.create! valid_attributes
        # Assuming there are no other entry_values in the database, this
        # specifies that the EntryValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EntryValue.any_instance.should_receive(:update_attributes).with({ "entry_field_id" => "1" })
        put :update, {:id => entry_value.to_param, :entry_value => { "entry_field_id" => "1" }}, valid_session
      end

      it "assigns the requested entry_value as @entry_value" do
        entry_value = EntryValue.create! valid_attributes
        put :update, {:id => entry_value.to_param, :entry_value => valid_attributes}, valid_session
        assigns(:entry_value).should eq(entry_value)
      end

      it "redirects to the entry_value" do
        entry_value = EntryValue.create! valid_attributes
        put :update, {:id => entry_value.to_param, :entry_value => valid_attributes}, valid_session
        response.should redirect_to(entry_value)
      end
    end

    describe "with invalid params" do
      it "assigns the entry_value as @entry_value" do
        entry_value = EntryValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntryValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_value.to_param, :entry_value => { "entry_field_id" => "invalid value" }}, valid_session
        assigns(:entry_value).should eq(entry_value)
      end

      it "re-renders the 'edit' template" do
        entry_value = EntryValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EntryValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => entry_value.to_param, :entry_value => { "entry_field_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested entry_value" do
      entry_value = EntryValue.create! valid_attributes
      expect {
        delete :destroy, {:id => entry_value.to_param}, valid_session
      }.to change(EntryValue, :count).by(-1)
    end

    it "redirects to the entry_values list" do
      entry_value = EntryValue.create! valid_attributes
      delete :destroy, {:id => entry_value.to_param}, valid_session
      response.should redirect_to(entry_values_url)
    end
  end

end
